name: Todoy
description: A Todo App.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - fonts/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  fonts:
  - family: FiraCode
    fonts:
      - asset: fonts/FiraCode-Regular.ttf
      - asset: fonts/FiraCode-Italic.ttf

